# .travis.yml
language: go

go:
  - "1.11.x"
  - master

install:
  - go get -t ./...
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - env GO111MODULE=on go build 
  - env GO111MODULE=on go test
  - PATH="$HOME/gopath/bin:$PATH"
  - script/coverage --coveralls